import React from "react";
import {
	Book,
	FileText,
	Settings,
	Database,
	Server,
	Webhook,
	Zap,
	User,
	Users,
	Mail,
	Image,
	Link,
	Code,
	Terminal,
	MessageSquare,
	Send,
	Bell,
	Calendar,
	Clock,
	Lock,
	Shield,
	Cpu,
	Layers,
	Sparkles,
	Brain,
	Bot,
	Network,
	Globe,
	LayoutTemplate,
	Split,
	Combine,
	Fingerprint,
	Search as SearchIcon,
	Workflow,
	Play,
	CheckCircle,
	AlertCircle,
	HelpCircle,
	Activity,
	Box,
	Cloud,
	Eye,
	Headset,
	Star,
	Share2,
	Wrench,
} from "lucide-react";

export const ICONS: Record<string, React.ElementType> = {
	book: Book,
	"file-text": FileText,
	settings: Settings,
	database: Database,
	server: Server,
	webhook: Webhook,
	zap: Zap,
	user: User,
	users: Users,
	mail: Mail,
	image: Image,
	link: Link,
	code: Code,
	terminal: Terminal,
	"message-square": MessageSquare,
	send: Send,
	bell: Bell,
	calendar: Calendar,
	clock: Clock,
	lock: Lock,
	shield: Shield,
	cpu: Cpu,
	layers: Layers,
	sparkles: Sparkles,
	brain: Brain,
	bot: Bot,
	network: Network,
	globe: Globe,
	"layout-template": LayoutTemplate,
	split: Split,
	combine: Combine,
	fingerprint: Fingerprint,
	search: SearchIcon,
	workflow: Workflow,
	play: Play,
	"check-circle": CheckCircle,
	"alert-circle": AlertCircle,
	"help-circle": HelpCircle,
	activity: Activity,
	box: Box,
	cloud: Cloud,
	eye: Eye,
	headset: Headset,
	star: Star,
	share: Share2,
	wrench: Wrench,
};
