#!/usr/bin/env tsx
/**
 * sync-ai-context.ts
 *
 * Reads source AI context files and generates platform-specific rule files.
 * Run: npm run sync:context
 *
 * Sources (edit these):
 *   openspec/project.md
 *   .ai/ARCHITECTURE.md
 *   .ai/CONVENTIONS.md
 *   .ai/GUARDRAILS.md
 *   .ai/STACK.md
 *   .ai/GLOSSARY.md
 *   REJECTED_DECISIONS.md
 *
 * Outputs (auto-generated — do not edit directly):
 *   .cursor/rules/orchable.mdc           → Cursor IDE
 *   .windsurfrules                       → Windsurf IDE
 *   .agents/rules/project-context.md     → Antigravity (workspace-level)
 *   .github/copilot-instructions.md      → GitHub Copilot
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), '..');

// ──────────────────────────────────────────────────────────────────────────
// COLORS
// ──────────────────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
  bold: '\x1b[1m',
};

// ──────────────────────────────────────────────────────────────────────────
// SOURCE FILES
// ──────────────────────────────────────────────────────────────────────────
const SOURCES: Record<string, string> = {
  project: 'openspec/project.md',
  architecture: '.ai/ARCHITECTURE.md',
  conventions: '.ai/CONVENTIONS.md',
  guardrails: '.ai/GUARDRAILS.md',
  stack: '.ai/STACK.md',
  glossary: '.ai/GLOSSARY.md',
  rejected: 'REJECTED_DECISIONS.md',
};

function readSource(key: string): string {
  const filePath = path.join(ROOT, SOURCES[key]);
  if (!fs.existsSync(filePath)) {
    console.warn(`${C.yellow}⚠ Missing source: ${SOURCES[key]}${C.reset}`);
    return `<!-- Source not found: ${SOURCES[key]} -->`;
  }
  return fs.readFileSync(filePath, 'utf8').trim();
}

// ──────────────────────────────────────────────────────────────────────────
// HEADER / WARNING — prepended to every generated file
// ──────────────────────────────────────────────────────────────────────────
function generatedWarning(platform: string): string {
  return `<!-- ⚠️  AUTO-GENERATED — Do NOT edit this file directly.
     Source: openspec/project.md + .ai/  directory
     Regenerate: npm run sync:context
     Platform: ${platform}
-->`;
}

// ──────────────────────────────────────────────────────────────────────────
// BUILD CONTENT BLOCKS
// ──────────────────────────────────────────────────────────────────────────
function buildFullContext(sources: Record<string, string>): string {
  return `# Orchable AI Context

${sources.project}

---

# Architecture Reference

${sources.architecture}

---

# Coding Conventions

${sources.conventions}

---

# Guardrails & Rules

${sources.guardrails}

---

# Tech Stack

${sources.stack}

---

# Glossary

${sources.glossary}

---

# Rejected Decisions (Anti-Patterns)

${sources.rejected}
`;
}

// Cursor uses a condensed version focused on rules and conventions
function buildCursorContent(sources: Record<string, string>): string {
  return `---
description: Orchable project rules for Cursor IDE
globs: ["**/*.ts", "**/*.tsx", "**/*.sql", "**/*.json"]
alwaysApply: true
---

${generatedWarning('Cursor')}

# Orchable Project Rules

${sources.project}

---

${sources.guardrails}

---

${sources.conventions}

---

${sources.stack}
`;
}

// Windsurf uses a flat markdown file — keep it focused
function buildWindsurfContent(sources: Record<string, string>): string {
  return `${generatedWarning('Windsurf')}

# Orchable AI Rules for Windsurf

${sources.project}

---

${sources.guardrails}

---

${sources.conventions}
`;
}

// GitHub Copilot — workspace instruction file
function buildCopilotContent(sources: Record<string, string>): string {
  return `${generatedWarning('GitHub Copilot')}

# Orchable – Copilot Instructions

${sources.project}

---

${sources.guardrails}

---

${sources.architecture}
`;
}

// ──────────────────────────────────────────────────────────────────────────
// WRITE FILE (only if changed)
// ──────────────────────────────────────────────────────────────────────────
function writeIfChanged(targetPath: string, content: string): 'written' | 'unchanged' {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (fs.existsSync(targetPath)) {
    const existing = fs.readFileSync(targetPath, 'utf8');
    if (existing === content) return 'unchanged';
  }

  fs.writeFileSync(targetPath, content, 'utf8');
  return 'written';
}

// ──────────────────────────────────────────────────────────────────────────
// OUTPUTS
// ──────────────────────────────────────────────────────────────────────────
interface OutputTarget {
  label: string;
  path: string;
  content: (s: Record<string, string>) => string;
}

const OUTPUTS: OutputTarget[] = [
  {
    label: 'Cursor',
    path: '.cursor/rules/orchable.mdc',
    content: buildCursorContent,
  },
  {
    label: 'Windsurf',
    path: '.windsurfrules',
    content: buildWindsurfContent,
  },
  {
    label: 'Antigravity (workspace)',
    path: '.agents/rules/project-context.md',
    content: (s) => `${generatedWarning('Antigravity')}\n\n${buildFullContext(s)}`,
  },
  {
    label: 'GitHub Copilot',
    path: '.github/copilot-instructions.md',
    content: buildCopilotContent,
  },
];

// ──────────────────────────────────────────────────────────────────────────
// MAIN
// ──────────────────────────────────────────────────────────────────────────
console.log(`${C.bold}${C.cyan}🔄 sync-ai-context${C.reset} — reading source files...\n`);

// Read all sources first (fail fast if any are missing badly)
let hasError = false;
const sources: Record<string, string> = {};

for (const [key, relPath] of Object.entries(SOURCES)) {
  const filePath = path.join(ROOT, relPath);
  if (!fs.existsSync(filePath)) {
    console.error(`${C.red}❌ Source missing: ${relPath}${C.reset}`);
    hasError = true;
  } else {
    sources[key] = fs.readFileSync(filePath, 'utf8').trim();
    console.log(`  ${C.green}✓${C.reset} read  ${relPath}`);
  }
}

if (hasError) {
  console.error(`\n${C.red}Aborting: one or more source files are missing.${C.reset}`);
  process.exit(1);
}

// Write all outputs
console.log(`\n${C.bold}Writing platform files:${C.reset}`);

let writtenCount = 0;
let unchangedCount = 0;

for (const target of OUTPUTS) {
  const content = target.content(sources);
  const targetPath = path.join(ROOT, target.path);
  const result = writeIfChanged(targetPath, content);

  if (result === 'written') {
    console.log(`  ${C.green}✅ written  ${target.path}${C.reset}  (${target.label})`);
    writtenCount++;
  } else {
    console.log(`  ${C.yellow}–  unchanged ${target.path}${C.reset}  (${target.label})`);
    unchangedCount++;
  }
}

console.log(
  `\n${C.bold}Done.${C.reset} ${writtenCount} written, ${unchangedCount} unchanged.\n`
);
process.exit(0);
